# Generated by Django 4.0.5 on 2022-09-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_requirement_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_details',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
