# Generated by Django 4.0.5 on 2022-09-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_requirement_details_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_requirement_details',
            name='final',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
