# Generated by Django 4.0.5 on 2022-09-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientregistration',
            new_name='analysisregistration',
        ),
    ]
